name: Validate List Universitas

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    
    - name: Install Validation Dependencies
      working-directory: .\_test\
      run: pip install -r .\requirements.txt
      
    - name: Validate JSON with Python Script
      working-directory: .\_test
      run: |
        python .\main.py
